name = "pikaia"
author = "Jacob Williams"
copyright  = "Copyright (c) 2015-2024, Jacob Williams"
license = "BSD-3"
description = "Modern Fortran Edition of the Pikaia Genetic Algorithm"
homepage = "https://github.com/jacobwilliams/pikaia"
keywords = ["optimization", "genetic algorithms"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true

[dependencies]
mersenne-twister-fortran = { git="https://github.com/jacobwilliams/mersenne-twister-fortran.git", tag = "1.0.1" }

[dev-dependencies]
json-fortran = { git="https://github.com/jacobwilliams/json-fortran.git"}

[library]
source-dir = "src"

[install]
library = true