solve_with_pikaia – Pikaia
solve_with_pikaia Subroutine
Jacob Williams
15 statements
Source File
private subroutine solve_with_pikaia(me, x, f, status)
Main pikaia wrapper used by the class.
Type Bound
pikaia_class
Arguments
Type Intent Optional Attributes Name
class(pikaia_class), intent(inout) :: me
real(kind=wp), intent(inout), dimension(:) :: x
real(kind=wp), intent(out) :: f
integer, intent(out) :: status
Calls
Source Code
    subroutine solve_with_pikaia(me,x,f,status)
    implicit none
    class(pikaia_class),intent(inout)   :: me
    real(wp),dimension(:),intent(inout) :: x
    real(wp),intent(out)                :: f
    integer,intent(out)                 :: status
    if (associated(me%user_f)) then
        !scale input initial guess to be [0,1]:
        x = (x-me%xl)/me%del
        !call the main routine, using the wrapper function:
        call me%pikaia(x,f,status)
        !unscale output to be [xl,xu]:
        x = me%xl + me%del*x
    else
        write(output_unit,'(A)') 'Error: pikaia class not initialized.'
        status = -1
    end if
    end subroutine solve_with_pikaia
Call graph
solve_with_pikaia calls pikaia
pikaia calls adjmut, cross, decode, encode, func_wrapper, genrep, mutate, newpop, report, rninit, rnkpop, select_parents, stdrep, urand
cross calls urand
mutate calls urand
newpop calls func_wrapper, rnkpop
rninit calls initialize
rnkpop calls rqsort
select_parents calls urand
stdrep calls urand
urand calls genrand64_real1