name: CI
on: [push]
jobs:

  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [10] # Version of GFortran we want to use.
        python-version: [3.9]
        open-mp: ['yes', 'no']
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Python
      uses: actions/setup-python@v1 # Use pip to install latest CMake, & FORD/Jin2For, etc.
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Setup Fortran Package Manager
      uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Python dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install ford
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install GFortran Linux
      if: contains( matrix.os, 'ubuntu')
      run: |
        sudo apt-get install lcov
        sudo update-alternatives \
           --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc_v }} 100 \
           --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc_v }} \
           --slave /usr/bin/gcov gcov /usr/bin/gcov-${{ matrix.gcc_v }}

    # - name: Compile-OpenMP
    #   if: contains( matrix.open-mp, 'yes')
    #   run: FoBiS.py build -f pikaia.fobis -mode tests-gnu-openmp

    # - name: Compile
    #   if: contains( matrix.open-mp, 'no')
    #   run: FoBiS.py build -f pikaia.fobis -mode tests-gnu

    - name: Run tests (OpenMP)
      if: contains( matrix.open-mp, 'yes')
      run: fpm test --profile debug --flag -fopenmp

    - name: Run tests
      if: contains( matrix.open-mp, 'no')
      run: fpm test --profile debug --flag -coverage

    - name: Create coverage report
      run: |
        mkdir -p ${{ env.COV_DIR }}
        lcov --capture --initial --base-directory . --directory build/gfortran_*/ --output-file ${{ env.COV_DIR }}/coverage.base
        lcov --capture --base-directory . --directory build/gfortran_*/ --output-file ${{ env.COV_DIR }}/coverage.capture
        lcov --add-tracefile ${{ env.COV_DIR }}/coverage.base --add-tracefile ${{ env.COV_DIR }}/coverage.capture --output-file ${{ env.COV_DIR }}/coverage.info
      env:
        COV_DIR: build/coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        files: build/coverage/coverage.info

    - name: Build documentation
      if: contains( matrix.open-mp, 'no')
      run: ford ./pikaia.md

    - name: Deploy Documentation
      if: github.ref == 'refs/heads/master' && contains( matrix.open-mp, 'no')
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc  # The folder the action should deploy.
